/**
 * Single source of truth for the Elixir ↔ Node sidecar wire protocol.
 *
 * Mirrors `lib/claude_agent_sdk/json_rpc/protocol.ex` exactly. Every
 * method name, notification name, and payload shape in this file has a
 * counterpart in the Elixir module, and vice versa. A parity test on
 * the Elixir side enforces this at CI time.
 *
 * Framing: newline-delimited JSON-RPC 2.0 over stdio. One JSON object
 * per `\n` terminated line. Stdout carries JSON-RPC frames only.
 * Stderr is unstructured human log output and must never be parsed.
 *
 * Every `session.*` method and every session-scoped notification
 * carries a `sessionId`. The Elixir side generates the sessionId (UUID
 * v4) and passes it into `session.create`; the sidecar stores the
 * upstream `unstable_v2_createSession` handle keyed by it.
 */

// ---------------------------------------------------------------------------
// Protocol version
// ---------------------------------------------------------------------------

export const PROTOCOL_VERSION = "1.0" as const;

// ---------------------------------------------------------------------------
// Methods — Elixir → Node (request/response)
// ---------------------------------------------------------------------------

export const METHOD_SESSION_CREATE = "session.create" as const;
export const METHOD_SESSION_SEND = "session.send" as const;
export const METHOD_SESSION_STREAM_START = "session.stream.start" as const;
export const METHOD_SESSION_STREAM_CANCEL = "session.stream.cancel" as const;
export const METHOD_SESSION_RESUME = "session.resume" as const;
export const METHOD_SESSION_CLOSE = "session.close" as const;
export const METHOD_PING = "ping" as const;
export const METHOD_SHUTDOWN = "shutdown" as const;

// ---------------------------------------------------------------------------
// Methods — Node → Elixir (request/response)
// ---------------------------------------------------------------------------

export const METHOD_HOOK_FIRE = "hook.fire" as const;
export const METHOD_MCP_CALL = "mcp.call" as const;

// ---------------------------------------------------------------------------
// Notifications (no id, no response)
// ---------------------------------------------------------------------------

export const NOTIF_SIDECAR_READY = "sidecar.ready" as const;
export const NOTIF_STREAM_MESSAGE = "stream.message" as const;
export const NOTIF_STREAM_END = "stream.end" as const;
export const NOTIF_STREAM_ERROR = "stream.error" as const;
export const NOTIF_LOG = "log" as const;

// ---------------------------------------------------------------------------
// Aggregate const arrays (keep parity checker happy on both sides)
// ---------------------------------------------------------------------------

export const METHODS = [
  METHOD_SESSION_CREATE,
  METHOD_SESSION_SEND,
  METHOD_SESSION_STREAM_START,
  METHOD_SESSION_STREAM_CANCEL,
  METHOD_SESSION_RESUME,
  METHOD_SESSION_CLOSE,
  METHOD_PING,
  METHOD_SHUTDOWN,
  METHOD_HOOK_FIRE,
  METHOD_MCP_CALL,
] as const;

export const NOTIFICATIONS = [
  NOTIF_SIDECAR_READY,
  NOTIF_STREAM_MESSAGE,
  NOTIF_STREAM_END,
  NOTIF_STREAM_ERROR,
  NOTIF_LOG,
] as const;

export type MethodName = (typeof METHODS)[number];
export type NotificationName = (typeof NOTIFICATIONS)[number];

// ---------------------------------------------------------------------------
// Error codes (JSON-RPC 2.0 reserves −32768..−32000)
// ---------------------------------------------------------------------------

export const ERROR_PARSE = -32700 as const;
export const ERROR_INVALID_REQUEST = -32600 as const;
export const ERROR_METHOD_NOT_FOUND = -32601 as const;
export const ERROR_INVALID_PARAMS = -32602 as const;
export const ERROR_INTERNAL = -32603 as const;

export const ERROR_SESSION_UNKNOWN = -32001 as const;
export const ERROR_SESSION_CLOSED = -32002 as const;
export const ERROR_STREAM_CANCELLED = -32003 as const;
export const ERROR_HOOK_FAILED = -32004 as const;
export const ERROR_MCP_FAILED = -32005 as const;
export const ERROR_SIDECAR_SHUTTING_DOWN = -32006 as const;

// ---------------------------------------------------------------------------
// Shared primitive types
// ---------------------------------------------------------------------------

/** Opaque session identifier. UUID v4 string generated by Elixir. */
export type SessionId = string;

/** Opaque stream identifier, scoped within a session. */
export type StreamId = string;

/** JSON-RPC request id. */
export type RpcId = number | string;

/** Hook event names reachable over the sidecar. Mirrors hook_event on Elixir. */
export type HookEvent =
  | "pre_tool_use"
  | "post_tool_use"
  | "post_tool_use_failure"
  | "user_prompt_submit"
  | "stop"
  | "subagent_start"
  | "subagent_stop"
  | "pre_compact"
  | "notification"
  | "permission_request"
  | "session_start"
  | "session_end"
  | "setup"
  | "teammate_idle"
  | "task_completed"
  | "config_change"
  | "worktree_create"
  | "worktree_remove";

// ---------------------------------------------------------------------------
// Request params / results — Elixir → Node
// ---------------------------------------------------------------------------

export interface SessionCreateParams {
  sessionId: SessionId;
  /** TS SDK option shape (model, tools, hooks event list, mcp descriptors, …). */
  options: Record<string, unknown>;
  /** Names of hook events the caller wants dispatched to Elixir for this session. */
  hookEvents?: string[];
  /** Descriptors for Elixir-authored MCP tools this session should expose. */
  mcpTools?: McpToolDescriptor[];
}

export interface SessionCreateResult {
  sessionId: SessionId;
  createdAt: string;
}

export interface SessionSendParams {
  sessionId: SessionId;
  message: Record<string, unknown>;
}

export interface SessionSendResult {
  accepted: boolean;
}

export interface SessionStreamStartParams {
  sessionId: SessionId;
  streamId: StreamId;
}

export interface SessionStreamStartResult {
  streamId: StreamId;
}

export interface SessionStreamCancelParams {
  sessionId: SessionId;
  streamId: StreamId;
}

export interface SessionStreamCancelResult {
  cancelled: boolean;
}

export interface SessionResumeParams {
  sessionId: SessionId;
  options?: Record<string, unknown>;
}

export interface SessionResumeResult {
  sessionId: SessionId;
  resumedAt: string;
}

export interface SessionCloseParams {
  sessionId: SessionId;
}

export interface SessionCloseResult {
  closed: boolean;
}

export interface PingParams {
  // intentionally empty
}

export interface PingResult {
  pong: boolean;
  serverTime: string;
}

export interface ShutdownParams {
  graceMs?: number;
}

export interface ShutdownResult {
  shuttingDown: boolean;
}

// ---------------------------------------------------------------------------
// Request params / results — Node → Elixir
// ---------------------------------------------------------------------------

export interface HookFireParams {
  sessionId: SessionId;
  event: HookEvent;
  payload: Record<string, unknown>;
}

/**
 * Caller's Elixir hook callback return value normalized to JSON.
 * `decision` is one of "allow" | "deny" | "continue" | "block" | "ask".
 */
export interface HookFireResult {
  decision?: "allow" | "deny" | "continue" | "block" | "ask";
  reason?: string;
  systemMessage?: string;
  modifiedInput?: Record<string, unknown>;
}

export interface McpToolDescriptor {
  server: string;
  tool: string;
  /** JSON-schema describing the tool's input parameters. */
  inputSchema: Record<string, unknown>;
  description?: string;
}

export interface McpCallParams {
  sessionId: SessionId;
  server: string;
  tool: string;
  args: Record<string, unknown>;
}

export interface McpCallResult {
  content: Array<Record<string, unknown>>;
  isError?: boolean;
}

// ---------------------------------------------------------------------------
// Notification payloads
// ---------------------------------------------------------------------------

export interface SidecarReadyParams {
  protocolVersion: string;
  sidecarVersion: string;
  sdkVersion: string;
  nodeVersion: string;
}

export interface StreamMessageParams {
  sessionId: SessionId;
  streamId: StreamId;
  /** One SDK message object (text_delta, tool_use, message_stop, thinking_delta, …). */
  message: Record<string, unknown>;
}

export interface StreamEndParams {
  sessionId: SessionId;
  streamId: StreamId;
  reason: string;
}

export interface StreamErrorParams {
  sessionId: SessionId;
  streamId?: StreamId;
  error: {
    code: number;
    message: string;
    data?: unknown;
  };
}

export interface LogParams {
  level: "debug" | "info" | "warn" | "error";
  message: string;
  sessionId?: SessionId;
  fields?: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// JSON-RPC envelopes
// ---------------------------------------------------------------------------

export interface JsonRpcRequest<P = Record<string, unknown>> {
  jsonrpc: "2.0";
  id: RpcId;
  method: string;
  params: P;
}

export interface JsonRpcNotification<P = Record<string, unknown>> {
  jsonrpc: "2.0";
  method: string;
  params: P;
}

export interface JsonRpcSuccessResponse<R = unknown> {
  jsonrpc: "2.0";
  id: RpcId;
  result: R;
}

export interface JsonRpcErrorResponse {
  jsonrpc: "2.0";
  id: RpcId;
  error: {
    code: number;
    message: string;
    data?: unknown;
  };
}

export type JsonRpcResponse<R = unknown> =
  | JsonRpcSuccessResponse<R>
  | JsonRpcErrorResponse;

// ---------------------------------------------------------------------------
// Method → (params, result) type lookup — compile-time checks on both sides
// ---------------------------------------------------------------------------

export interface MethodMap {
  [METHOD_SESSION_CREATE]: { params: SessionCreateParams; result: SessionCreateResult };
  [METHOD_SESSION_SEND]: { params: SessionSendParams; result: SessionSendResult };
  [METHOD_SESSION_STREAM_START]: {
    params: SessionStreamStartParams;
    result: SessionStreamStartResult;
  };
  [METHOD_SESSION_STREAM_CANCEL]: {
    params: SessionStreamCancelParams;
    result: SessionStreamCancelResult;
  };
  [METHOD_SESSION_RESUME]: { params: SessionResumeParams; result: SessionResumeResult };
  [METHOD_SESSION_CLOSE]: { params: SessionCloseParams; result: SessionCloseResult };
  [METHOD_PING]: { params: PingParams; result: PingResult };
  [METHOD_SHUTDOWN]: { params: ShutdownParams; result: ShutdownResult };
  [METHOD_HOOK_FIRE]: { params: HookFireParams; result: HookFireResult };
  [METHOD_MCP_CALL]: { params: McpCallParams; result: McpCallResult };
}

export interface NotificationMap {
  [NOTIF_SIDECAR_READY]: SidecarReadyParams;
  [NOTIF_STREAM_MESSAGE]: StreamMessageParams;
  [NOTIF_STREAM_END]: StreamEndParams;
  [NOTIF_STREAM_ERROR]: StreamErrorParams;
  [NOTIF_LOG]: LogParams;
}
