defmodule ClaudeAgentSDK.JsonRpc.Protocol do
  @moduledoc """
  Single source of truth for the Elixir ↔ Node sidecar wire protocol.

  Mirrors `priv/ts_sidecar/src/protocol.ts` exactly. Every method name,
  notification name, and payload shape documented here has a counterpart
  in the TypeScript file, and vice versa. A parity test
  (`test/claude_agent_sdk/json_rpc/protocol_parity_test.exs`) enforces
  this at CI time.

  ## Framing

  Newline-delimited JSON-RPC 2.0 over stdio. One JSON object per `\\n`
  terminated line. Stdout carries JSON-RPC frames only. Stderr is
  unstructured human log output and must never be parsed.

  ## Direction

  Both sides may issue requests. A request carries an `id`; a
  notification does not. `jsonrpc` is always the string `"2.0"`.

  ## sessionId tagging

  Every `session.*` method carries a `sessionId` parameter. Every
  notification emitted by the Node side that relates to a logical
  session carries the `sessionId` it originated from. The Elixir
  `Sidecar.Worker` demultiplexes inbound frames by `sessionId` and
  routes them to the owning `Session` GenServer via `SessionRegistry`.

  `sessionId` is generated by Elixir (a UUID v4 string) and passed
  into `session.create`. The Node side stores the upstream
  `unstable_v2_createSession` handle keyed by that sessionId. Keeping
  the sessionId Elixir-generated means every outbound method on both
  sides uniformly carries it — no "session-pending" state.
  """

  # ---------------------------------------------------------------------------
  # Protocol version
  # ---------------------------------------------------------------------------

  @protocol_version "1.0"

  @doc "Semantic version of the wire protocol. Bumped on breaking changes."
  @spec protocol_version() :: String.t()
  def protocol_version, do: @protocol_version

  # ---------------------------------------------------------------------------
  # Methods — Elixir → Node (request/response)
  # ---------------------------------------------------------------------------

  @method_session_create "session.create"
  @method_session_send "session.send"
  @method_session_stream_start "session.stream.start"
  @method_session_stream_cancel "session.stream.cancel"
  @method_session_resume "session.resume"
  @method_session_close "session.close"
  @method_ping "ping"
  @method_shutdown "shutdown"

  # ---------------------------------------------------------------------------
  # Methods — Node → Elixir (request/response)
  # ---------------------------------------------------------------------------

  @method_hook_fire "hook.fire"
  @method_mcp_call "mcp.call"

  # ---------------------------------------------------------------------------
  # Notifications (no id, no response)
  # ---------------------------------------------------------------------------

  @notif_sidecar_ready "sidecar.ready"
  @notif_stream_message "stream.message"
  @notif_stream_end "stream.end"
  @notif_stream_error "stream.error"
  @notif_log "log"

  # ---------------------------------------------------------------------------
  # Error codes (JSON-RPC 2.0 reserves −32768..−32000)
  # ---------------------------------------------------------------------------

  @error_parse -32700
  @error_invalid_request -32600
  @error_method_not_found -32601
  @error_invalid_params -32602
  @error_internal -32603

  @error_session_unknown -32001
  @error_session_closed -32002
  @error_stream_cancelled -32003
  @error_hook_failed -32004
  @error_mcp_failed -32005
  @error_sidecar_shutting_down -32006

  # ---------------------------------------------------------------------------
  # Public accessors (keep names greppable on the Elixir side)
  # ---------------------------------------------------------------------------

  @spec methods() :: [String.t()]
  def methods do
    [
      @method_session_create,
      @method_session_send,
      @method_session_stream_start,
      @method_session_stream_cancel,
      @method_session_resume,
      @method_session_close,
      @method_ping,
      @method_shutdown,
      @method_hook_fire,
      @method_mcp_call
    ]
  end

  @spec notifications() :: [String.t()]
  def notifications do
    [
      @notif_sidecar_ready,
      @notif_stream_message,
      @notif_stream_end,
      @notif_stream_error,
      @notif_log
    ]
  end

  @spec error_codes() :: %{atom() => integer()}
  def error_codes do
    %{
      parse: @error_parse,
      invalid_request: @error_invalid_request,
      method_not_found: @error_method_not_found,
      invalid_params: @error_invalid_params,
      internal: @error_internal,
      session_unknown: @error_session_unknown,
      session_closed: @error_session_closed,
      stream_cancelled: @error_stream_cancelled,
      hook_failed: @error_hook_failed,
      mcp_failed: @error_mcp_failed,
      sidecar_shutting_down: @error_sidecar_shutting_down
    }
  end

  def method_session_create, do: @method_session_create
  def method_session_send, do: @method_session_send
  def method_session_stream_start, do: @method_session_stream_start
  def method_session_stream_cancel, do: @method_session_stream_cancel
  def method_session_resume, do: @method_session_resume
  def method_session_close, do: @method_session_close
  def method_ping, do: @method_ping
  def method_shutdown, do: @method_shutdown
  def method_hook_fire, do: @method_hook_fire
  def method_mcp_call, do: @method_mcp_call

  def notif_sidecar_ready, do: @notif_sidecar_ready
  def notif_stream_message, do: @notif_stream_message
  def notif_stream_end, do: @notif_stream_end
  def notif_stream_error, do: @notif_stream_error
  def notif_log, do: @notif_log

  # ---------------------------------------------------------------------------
  # Shared typespecs — payload shapes
  # ---------------------------------------------------------------------------

  @typedoc "Opaque session identifier. UUID v4 string generated by Elixir."
  @type session_id :: String.t()

  @typedoc "Opaque stream identifier, scoped within a session."
  @type stream_id :: String.t()

  @typedoc "JSON-RPC request id. Integer or string, per JSON-RPC 2.0."
  @type rpc_id :: integer() | String.t()

  @typedoc "Hook event names reachable over the sidecar."
  @type hook_event ::
          :pre_tool_use
          | :post_tool_use
          | :post_tool_use_failure
          | :user_prompt_submit
          | :stop
          | :subagent_start
          | :subagent_stop
          | :pre_compact
          | :notification
          | :permission_request
          | :session_start
          | :session_end
          | :setup
          | :teammate_idle
          | :task_completed
          | :config_change
          | :worktree_create
          | :worktree_remove

  # --- Request params -------------------------------------------------------

  @typedoc """
  Params for `session.create`.

  `options` is the TS SDK option shape (model, tools, hooks event list,
  mcp tool descriptors, …). The Elixir side serializes
  `ClaudeAgentSDK.Options` into this map.
  """
  @type session_create_params :: %{
          required(:sessionId) => session_id(),
          required(:options) => map(),
          optional(:hookEvents) => [String.t()],
          optional(:mcpTools) => [map()]
        }

  @type session_create_result :: %{
          required(:sessionId) => session_id(),
          required(:createdAt) => String.t()
        }

  @typedoc "Params for `session.send`."
  @type session_send_params :: %{
          required(:sessionId) => session_id(),
          required(:message) => map()
        }

  @type session_send_result :: %{required(:accepted) => boolean()}

  @typedoc "Params for `session.stream.start`."
  @type session_stream_start_params :: %{
          required(:sessionId) => session_id(),
          required(:streamId) => stream_id()
        }

  @type session_stream_start_result :: %{required(:streamId) => stream_id()}

  @typedoc "Params for `session.stream.cancel`."
  @type session_stream_cancel_params :: %{
          required(:sessionId) => session_id(),
          required(:streamId) => stream_id()
        }

  @type session_stream_cancel_result :: %{required(:cancelled) => boolean()}

  @typedoc "Params for `session.resume` (maps to `unstable_v2_resumeSession`)."
  @type session_resume_params :: %{
          required(:sessionId) => session_id(),
          optional(:options) => map()
        }

  @type session_resume_result :: %{
          required(:sessionId) => session_id(),
          required(:resumedAt) => String.t()
        }

  @typedoc "Params for `session.close`."
  @type session_close_params :: %{required(:sessionId) => session_id()}

  @type session_close_result :: %{required(:closed) => boolean()}

  @typedoc "Params for `ping`."
  @type ping_params :: %{}

  @type ping_result :: %{
          required(:pong) => boolean(),
          required(:serverTime) => String.t()
        }

  @typedoc "Params for `shutdown`."
  @type shutdown_params :: %{optional(:graceMs) => non_neg_integer()}

  @type shutdown_result :: %{required(:shuttingDown) => boolean()}

  # --- Node → Elixir request params ----------------------------------------

  @typedoc "Params for `hook.fire` (Node → Elixir)."
  @type hook_fire_params :: %{
          required(:sessionId) => session_id(),
          required(:event) => String.t(),
          required(:payload) => map()
        }

  @typedoc """
  Result of `hook.fire`. Shape mirrors the caller's Elixir hook
  callback return value normalized to JSON. `decision` is one of
  `"allow"`, `"deny"`, `"continue"`, `"block"`, or `"ask"`.
  """
  @type hook_fire_result :: %{
          optional(:decision) => String.t(),
          optional(:reason) => String.t(),
          optional(:systemMessage) => String.t(),
          optional(:modifiedInput) => map()
        }

  @typedoc "Params for `mcp.call` (Node → Elixir)."
  @type mcp_call_params :: %{
          required(:sessionId) => session_id(),
          required(:server) => String.t(),
          required(:tool) => String.t(),
          required(:args) => map()
        }

  @typedoc "Result of `mcp.call`. Mirrors MCP tool result envelope."
  @type mcp_call_result :: %{
          required(:content) => [map()],
          optional(:isError) => boolean()
        }

  # --- Notification payloads ------------------------------------------------

  @typedoc "Emitted once on sidecar boot."
  @type sidecar_ready_params :: %{
          required(:protocolVersion) => String.t(),
          required(:sidecarVersion) => String.t(),
          required(:sdkVersion) => String.t(),
          required(:nodeVersion) => String.t()
        }

  @typedoc "Single SDK message tagged with sessionId + streamId."
  @type stream_message_params :: %{
          required(:sessionId) => session_id(),
          required(:streamId) => stream_id(),
          required(:message) => map()
        }

  @typedoc "Stream completed normally."
  @type stream_end_params :: %{
          required(:sessionId) => session_id(),
          required(:streamId) => stream_id(),
          required(:reason) => String.t()
        }

  @typedoc """
  Per-session error from the sidecar. Does not indicate the sidecar
  process itself is unhealthy; the pipe stays open.
  """
  @type stream_error_params :: %{
          required(:sessionId) => session_id(),
          optional(:streamId) => stream_id(),
          required(:error) => %{
            required(:code) => integer(),
            required(:message) => String.t(),
            optional(:data) => any()
          }
        }

  @typedoc "Structured log line from the sidecar (human diagnostic)."
  @type log_params :: %{
          required(:level) => String.t(),
          required(:message) => String.t(),
          optional(:sessionId) => session_id(),
          optional(:fields) => map()
        }

  # --- JSON-RPC envelopes ---------------------------------------------------

  @typedoc "JSON-RPC 2.0 request envelope."
  @type request :: %{
          required(:jsonrpc) => String.t(),
          required(:id) => rpc_id(),
          required(:method) => String.t(),
          required(:params) => map()
        }

  @typedoc "JSON-RPC 2.0 notification envelope (no id)."
  @type notification :: %{
          required(:jsonrpc) => String.t(),
          required(:method) => String.t(),
          required(:params) => map()
        }

  @typedoc "JSON-RPC 2.0 success response."
  @type response_ok :: %{
          required(:jsonrpc) => String.t(),
          required(:id) => rpc_id(),
          required(:result) => any()
        }

  @typedoc "JSON-RPC 2.0 error response."
  @type response_error :: %{
          required(:jsonrpc) => String.t(),
          required(:id) => rpc_id(),
          required(:error) => %{
            required(:code) => integer(),
            required(:message) => String.t(),
            optional(:data) => any()
          }
        }
end
