defmodule ClaudeAgentSDK.JsonRpc.Protocol do
  @moduledoc """
  Single source of truth for the Elixir ↔ Node sidecar wire protocol.

  Mirrors `priv/ts_sidecar/src/protocol.ts` exactly.

  ## Framing

  Newline-delimited JSON-RPC 2.0 over stdio. Stdout carries JSON-RPC
  frames only. Stderr is unstructured human log output.

  ## sessionId tagging

  Every `session.*` method and every session-scoped notification carries
  a `sessionId` — a UUID v4 generated by Elixir. The sidecar stores the
  upstream `query()` handle keyed by it. The SDK's own internal
  session_id is separate and appears inside forwarded SDKMessage
  payloads.
  """

  @protocol_version "2.0"

  @spec protocol_version() :: String.t()
  def protocol_version, do: @protocol_version

  # Elixir → Node
  @method_session_create "session.create"
  @method_session_send "session.send"
  @method_session_control "session.control"
  @method_session_resume "session.resume"
  @method_session_close "session.close"
  @method_ping "ping"
  @method_shutdown "shutdown"

  # Node → Elixir
  @method_hook_fire "hook.fire"
  @method_mcp_call "mcp.call"
  @method_can_use_tool "can_use_tool"

  # Notifications
  @notif_sidecar_ready "sidecar.ready"
  @notif_session_message "session.message"
  @notif_session_error "session.error"
  @notif_session_closed "session.closed"
  @notif_log "log"

  @error_parse -32700
  @error_invalid_request -32600
  @error_method_not_found -32601
  @error_invalid_params -32602
  @error_internal -32603

  @error_session_unknown -32001
  @error_session_closed -32002
  @error_control_failed -32003
  @error_hook_failed -32004
  @error_mcp_failed -32005
  @error_sidecar_shutting_down -32006

  @spec methods() :: [String.t()]
  def methods do
    [
      @method_session_create,
      @method_session_send,
      @method_session_control,
      @method_session_resume,
      @method_session_close,
      @method_ping,
      @method_shutdown,
      @method_hook_fire,
      @method_mcp_call,
      @method_can_use_tool
    ]
  end

  @spec notifications() :: [String.t()]
  def notifications do
    [
      @notif_sidecar_ready,
      @notif_session_message,
      @notif_session_error,
      @notif_session_closed,
      @notif_log
    ]
  end

  @spec error_codes() :: %{atom() => integer()}
  def error_codes do
    %{
      parse: @error_parse,
      invalid_request: @error_invalid_request,
      method_not_found: @error_method_not_found,
      invalid_params: @error_invalid_params,
      internal: @error_internal,
      session_unknown: @error_session_unknown,
      session_closed: @error_session_closed,
      control_failed: @error_control_failed,
      hook_failed: @error_hook_failed,
      mcp_failed: @error_mcp_failed,
      sidecar_shutting_down: @error_sidecar_shutting_down
    }
  end

  def method_session_create, do: @method_session_create
  def method_session_send, do: @method_session_send
  def method_session_control, do: @method_session_control
  def method_session_resume, do: @method_session_resume
  def method_session_close, do: @method_session_close
  def method_ping, do: @method_ping
  def method_shutdown, do: @method_shutdown
  def method_hook_fire, do: @method_hook_fire
  def method_mcp_call, do: @method_mcp_call
  def method_can_use_tool, do: @method_can_use_tool

  def notif_sidecar_ready, do: @notif_sidecar_ready
  def notif_session_message, do: @notif_session_message
  def notif_session_error, do: @notif_session_error
  def notif_session_closed, do: @notif_session_closed
  def notif_log, do: @notif_log

  @typedoc "Opaque session identifier. UUID v4 string generated by Elixir."
  @type session_id :: String.t()

  @typedoc "Turn identifier returned from `session.send`."
  @type turn_id :: String.t()

  @type rpc_id :: integer() | String.t()

  @type session_create_params :: %{
          required(:sessionId) => session_id(),
          required(:options) => map(),
          optional(:permissionBridge) => boolean(),
          optional(:hookEvents) => [String.t()]
        }

  @type session_create_result :: %{
          required(:sessionId) => session_id(),
          required(:createdAt) => String.t()
        }

  @type session_send_params :: %{
          required(:sessionId) => session_id(),
          required(:content) => String.t(),
          optional(:turnId) => turn_id()
        }

  @type session_send_result :: %{required(:turnId) => turn_id()}

  @type session_control_params :: %{
          required(:sessionId) => session_id(),
          required(:method) => String.t(),
          optional(:args) => list()
        }

  @type session_control_result :: %{required(:value) => any()}

  @type session_resume_params :: %{
          required(:sessionId) => session_id(),
          required(:sdkSessionId) => String.t(),
          required(:options) => map()
        }

  @type session_resume_result :: %{
          required(:sessionId) => session_id(),
          required(:resumedAt) => String.t()
        }

  @type session_close_params :: %{required(:sessionId) => session_id()}

  @type session_close_result :: %{required(:closed) => boolean()}

  @type ping_result :: %{
          required(:pong) => boolean(),
          required(:serverTime) => String.t()
        }

  @type shutdown_result :: %{required(:shuttingDown) => boolean()}

  @type hook_fire_params :: %{
          required(:sessionId) => session_id(),
          required(:event) => String.t(),
          required(:payload) => map()
        }

  @type hook_fire_result :: %{
          optional(:decision) => String.t(),
          optional(:reason) => String.t(),
          optional(:systemMessage) => String.t(),
          optional(:modifiedInput) => map()
        }

  @type mcp_call_params :: %{
          required(:sessionId) => session_id(),
          required(:server) => String.t(),
          required(:tool) => String.t(),
          required(:args) => map()
        }

  @type mcp_call_result :: %{
          required(:content) => [map()],
          optional(:isError) => boolean()
        }

  @type can_use_tool_params :: %{
          required(:sessionId) => session_id(),
          required(:toolName) => String.t(),
          required(:input) => map()
        }

  @type can_use_tool_result ::
          %{required(:behavior) => String.t(), optional(:updatedInput) => map()}
          | %{
              required(:behavior) => String.t(),
              required(:message) => String.t(),
              optional(:interrupt) => boolean()
            }

  @type sidecar_ready_params :: %{
          required(:protocolVersion) => String.t(),
          required(:sidecarVersion) => String.t(),
          required(:sdkVersion) => String.t(),
          required(:nodeVersion) => String.t()
        }

  @type session_message_params :: %{
          required(:sessionId) => session_id(),
          required(:message) => map()
        }

  @type session_error_params :: %{
          required(:sessionId) => session_id(),
          required(:error) => %{
            required(:code) => integer(),
            required(:message) => String.t(),
            optional(:data) => any()
          }
        }

  @type session_closed_params :: %{
          required(:sessionId) => session_id(),
          required(:reason) => String.t()
        }

  @type log_params :: %{
          required(:level) => String.t(),
          required(:message) => String.t(),
          optional(:sessionId) => session_id(),
          optional(:fields) => map()
        }

  @type request :: %{
          required(:jsonrpc) => String.t(),
          required(:id) => rpc_id(),
          required(:method) => String.t(),
          required(:params) => map()
        }

  @type notification :: %{
          required(:jsonrpc) => String.t(),
          required(:method) => String.t(),
          required(:params) => map()
        }

  @type response_ok :: %{
          required(:jsonrpc) => String.t(),
          required(:id) => rpc_id(),
          required(:result) => any()
        }

  @type response_error :: %{
          required(:jsonrpc) => String.t(),
          required(:id) => rpc_id(),
          required(:error) => %{
            required(:code) => integer(),
            required(:message) => String.t(),
            optional(:data) => any()
          }
        }
end
